### ISSUE TITLE
シングルクォーテーションの除去

### ISSUE THREAD

**Issue by kotaYkw** [enpitut2020/blending-software_summer#69]
検索結果のチャンネル名にシングルクォーテーションが含まれてしまっている。

**Comment by madamaya** [comment]
406167f3455e67061155973a6f8114d2ae56792f で修正．
`app/views/posts/result.html.erb`を修正．
シングルクォーテーションがついて表示されるようになっていたデータを表示するときに，`gsub`関数を使ってシングルクォーテーションを空文字列に置換するようにしました．
